### ISSUE TITLE
velocity calculation dtype error

### ISSUE THREAD

**Issue by niklundgren** [nanotheorygroup/kaldo#13]
If asking for phonons.velocity on an amorphous system, the sij is cast as a float and an error is thrown.
Inserting the following line fixed it: sij = tf.cast(sij, dtype=tf.complex128), but the values were zero.
Instead, I think we should either explain and return sij if its amorphous, or throw an error.

Error:
tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute Mul as input 1(zero-based) was expected to be a complex128 tensor but is a double tensor [Op:Mul]

Full logs:
[log.txt](https://github.com/nanotheorygroup/kaldo/files/5632780/log.txt)

**Comment by gbarbalinardo** [comment]
Please add a case for is_amorphous where the square root of the frequency is a float. That should solve the casting problem.

**Comment by gbarbalinardo** [comment]
It looks good now.
