### ISSUE TITLE
With a specific combination of Ubuntu/ASE, the dynamical matrix and the third order matrices are zeros.

### ISSUE THREAD

**Issue by gbarbalinardo** [nanotheorygroup/kaldo#20]
Unfortunately, I don't know the details, but I heard this from @afiorent, and I heard @ZKC19940412 had a similar problem in the past. Maybe we can share the solution and figure out what to do about it here.

**Comment by ddonadio** [comment]
I experienced the same issue. It is happening with Ubuntu20 and the ASE interface. I do not think that it is a bug in kALDo, but having some checkpoint when the force constant tensors are constructed may help us figure it out. At present, it can be circumvented by computing the force constants with external tools, e.g. with lammps, but it limits the use of different calculators with kALDo.

**Comment by gbarbalinardo** [comment]
Closing since we weren't able to reproduce the issue.
