### ISSUE TITLE
CircleCI

### ISSUE THREAD

**Issue by niklundgren** [nanotheorygroup/kaldo#25]
Unit tests pass completion on my own workstation but fail on CircleCI.
Likely that some sort of configuration needs an edit.

**Comment by gbarbalinardo** [comment]
Do you have access to the CircleCI logs?

**Comment by niklundgren** [comment]
Yes, I've compared branches that passed and didn't pass, and there were two
lines of difference, mostly in documentation. Also, when I run the tests on
my own machine, they pass.

**Comment by niklundgren** [comment]
After adjusting the requirements.txt to keep the sparse version at 0.11.2, the CircleCI builds succeed.
Issue resolved with commit from fix/circleci
Possible adaptation to later versions of required packages can be explored in a future branch.

**Comment by niklundgren** [comment]
closed by fix on commit dbd13c9
