### ISSUE TITLE
Problem of calculating third order force constants

### ISSUE THREAD

**Issue by JWCheys** [nanotheorygroup/kaldo#36]
Dear developer,

I have successfully installed the modified version of LAMMPS. But when I try to  calculate third order  force constants using LAMMPS, I got the following errors:

**fmt::format_error: invalid format string
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0**

 I really don't know how to solve this problem. So, I'd like to seek your help. Thanks very much!
Best regards

**Comment by niklundgren** [comment]
Hello,
This is a difficult problem to diagnose based only on your error message.
If you’d like to share your input scripts I’d be happy to take a look.
My first suggestion is to ensure lammps was compiled correctly by running
the example lammps script found in
‘<lammpsdir>/examples/USER/phonon/dynamicalmatrixcommand/Silicon/‘. If that
works, we can move on from there. Please run it with MPI as well to ensure
the parallelization is working properly.

**Comment by JWCheys** [comment]
Hi,
According to your suggestion, I tested the example of Silicon with MPI and found dynamical_matrix command is working properly. Furthermore, I tested the command third_order, but I got the following errors:

**fmt::format_error: invalid format string
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[mpiexec@mu01] handle_pmi_cmd (./pm/pmiserv/pmiserv_cb.c:52): Unrecognized PMI command: abort | cleaning up processes
[mpiexec@mu01] control_cb (./pm/pmiserv/pmiserv_cb.c:289): unable to process PMI command
[mpiexec@mu01] HYDT_dmxu_poll_wait_for_event (./tools/demux/demux_poll.c:77): callback returned error status
[mpiexec@mu01] HYD_pmci_wait_for_completion (./pm/pmiserv/pmiserv_pmci.c:181): error waiting for event
[mpiexec@mu01] main (./ui/mpich/mpiexec.c:405): process manager error waiting for completion**

So, I think the problem is that third_order command is not working properly in my LAMMPS installation.

**Comment by niklundgren** [comment]
It's unclear from your error whether that's something machine specific, or an issue with the lammps version. Which lammps commit did you compile?
If you didn't already, I'd reccomend switching to the lammps stable branch
** in your lammps directory **
git checkout stable
** recompile **

The developer for the third_order command in LAMMPS has a separate experimental repo. It hasn't been merged into the LAMMPS master yet, but there's an open PR for it. You could try compiling from that branch:
git clone https://github.com/charlessievers/lammps
git checkout fed47b9ffc833bebffe0e460739ebd6ff69e9c8d

**Comment by niklundgren** [comment]
Going to close with a commit that directs people to a working commit of the OptimizedDynamicalMatrix command.

**Comment by JWCheys** [comment]
Thanks very much for you help.
Best regards.
