### ISSUE TITLE
QHGK

### ISSUE THREAD

**Issue by ZengZezhu** [nanotheorygroup/kaldo#4]
It is a so nice software!!! Thank you so much!

**Comment by ZengZezhu** [comment]
Hi,

I successfully installed the kaldo and tested the example_1. If I changed the storage format from numpy to formatted, then I can obtain the velocity matrix at all qpoints for all bands. However, the output velocity matrix only included the diagonal elements of group velocity(V(q)_{ii}). Is there any way to also obtain the off-diagonal velocity matrix (V(q)_{ij, i != j }). 

The reason that I want to obtain the off-diagonal velocity matrix is that I want to use it to calculate the off-diagonal thermal conductivity(or called coherence thermal conductivity in the paper of ''Unified theory of thermal transport in crystals and glasses'') (I attached this paper in this issue)

I  can compare the thermal conductivity from unified theory (Nature Physics) and qhgk method if I obtain the off-diagonal velocity matrix.  

Actually I also implemented the formula (Equation.26) in the Nature physics paper to calculate the total kappa(kappa_diagonal + kappa_off_diagonal), however, I am not sure my script is totally right. :)

If you need any more information, please contact me without any hesitation.

**Comment by gbarbalinardo** [comment]
Hi ZengZezhu, please contact me via email and I can try to help you out.

**Comment by ZengZezhu** [comment]
Thank you so much, I will contact you by email.
