### ISSUE TITLE
Questions about the stored binary files "_ps_and_gamma.npy”

### ISSUE THREAD

**Issue by OliverYL** [nanotheorygroup/kaldo#45]
Dear developers,

I did some calculation of the 3rd phonon bandwidths for tersoff-Si using the force constants from lammps with kaldo. I had finished the calculation but encounterd some confusing problems. I am writing to seek your help and the following are my questions.

1. **What's the meaning of data stored in file “_ps_and_gamma.npy”?** I found that the second column is the phonon bandwidth but the first column is smaller. 
2. **Is it possible for kaldo to export the information of generated k points?** The Phonons API only defines the number of k points and doesn’t return any information of k points.
3. I took the primitive cell (not orthogonal) and conventional cell (8 atoms, orthogonal) of diamond silicon respectively but get quite different density of phonon states and bandwidth/lifetime results. I did the test on using different  broadening_shape, kpts, temperature, broadening_shape parameters and the situation is the same. **Does kaldo have any restrictions for the input cell?**

Thank you very much!

Best regards

**Comment by gbarbalinardo** [comment]
Hi @OliverYL , 

I am replying here to both the issue and the email.

1. If you select to store your files in Numpy format,`_ps_and_gamma.npy` has the information about phase space and bandwidth (gamma). For RTA and QHGK the first column is the phase space, while the second is the bandwidth, analogous to [Phonons.bandwidth](https://nanotheorygroup.github.io/kaldo/docsource/api_phonons.html#kaldo.phonons.Phonons.bandwidth) and [Phonons.phase_space](https://nanotheorygroup.github.io/kaldo/docsource/api_phonons.html#kaldo.phonons.Phonons.phase_space).
2. Yes, you can save any property of the `Phonons`, `Conductivity` or `ForceConstants` objects. Once you created the `Phonons` object with something like `phonons = Phonons(...)`, use `np.save('filename', phonons.kpts)` to store it as a NumPy array.
3. As far as I know, kALDo doesn't have restrictions for the input cell. Can you share the input files via email, please?
