### ISSUE TITLE
Exporting 3rd force constants using kaldo

### ISSUE THREAD

**Issue by OliverYL** [nanotheorygroup/kaldo#57]
Dear developers,

Is it possible for _kaldo_ to export the 3rd force constants as the file format that can be used in other software, like _Phono3py_, or _hiPhive_? Thank you~

**Comment by ZKC19940412** [comment]
Hi, Oliver. Thank you so much for reaching out. Possible ways to export 3rd forces constants from kALDo to phonon3py or hiPhive might be achieved using hiPhive's in house routine to intake 3rd forces and reformat it (internally) as a force constant potentials. More details can be found in the following link: https://hiphive.materialsmodeling.org/advanced_topics/fcs_sensing.html. 

Once force constants are properly represented/reformatted as a force constant potentials, there are also in-house routines from hiPhive which you can convert a force constant potentials to force constants in format recognizable by Phonon3py and ShengBTE.

Hope this helps.

Best, 
Zekun

**Comment by OliverYL** [comment]
Dear Zekun,

Thank you for the prompt reply. It helps and I will try.

Bests,
Oliver
