### ISSUE TITLE
Different results of thermal conductivity in example 'amorphous_silicon_Tersoff_LAMMPS'

### ISSUE THREAD

**Issue by uucai** [nanotheorygroup/kaldo#85]
Hi,
I got two different results of thermal conductivity when running the script '2_aSi512_Tersoff_visualize_QHGK_properties.py' in example 'amorphous_silicon_Tersoff_LAMMPS'. The result printed is about 1.24 W/mK.  But, the result shown in the figure is about 1.1 W/mK. I found this difference is resulted from the different choice of diffusivity_bandwidth. The former directly uses the bandwidth computed by Phonons object. The latter uses the half of bandwidth computed by Phonons object, according to the line 278 in 'conductivity.py'. Could you tell me which one is correct for QHGK method?  Thank you in  advance.

**Comment by ZKC19940412** [comment]
Hi Zhuangli. Thank you so much for your interest in using kALDo and pointing out the different results in the calculations. The right result is obtained with full bandwidth. Please feel free to let us know if you have more questions.


Best, 
Zekun
