### ISSUE TITLE
How to get generalized group velocities and specific heat without 3rd force constants

### ISSUE THREAD

**Issue by uucai** [nanotheorygroup/kaldo#88]
Hi developers, 

I have obtained phonon bandwidths of a big system through extropolating those of a small system using the script in the example "amorphous_si_with_extrapolation". But I cannot use 'ForceConstants.from_folder' method to build the 'Forceconstants' instance with only 2nd order force constants and then 'Phonons' instance. As a result, I cannot get the generalized group velocity and generalized specific heat to calculate the thermal conductivity. I didn't see any clues about achieving it in examples. If you can give me any advice, I will appreacite it very much.

Best regards,
Zhuangli Cai

**Comment by ZKC19940412** [comment]
Hi, Zhuangli. Thanks for reaching out and using kALDo for your research. According to the forceconstants API, you can import only 2nd order force constants by specifying the flag only_second=True (More can be found starting from line 80 of https://github.com/nanotheorygroup/kaldo/blob/main/kaldo/forceconstants.py file).  

Hope this helps. Feel free to learn us know if you have more follow up questions.

Best, 
Zekun

**Comment by uucai** [comment]
Hi Zekun,

Thank you so much for your quick reply! I will try it.

Best wishes,
Zhuangli
