### ISSUE TITLE
Can KALDo be used for two dimensional material ? 

### ISSUE THREAD

**Issue by mu-dian** [nanotheorygroup/kaldo#90]
I have repeated an example called "amorphous_silicon_Tersoff_LAMMPS" in KALDo's example file. 
So I try to calculate the thermal conductivity of 2D material. Unfortunately, when I use the command "forceconstants = ForceConstants.from_folder(folder='fc_alpha',supercell=supercell,format='lammps')", it comes out an error: "numpy.linalg.LinAlgError: Singular matrix". I think maybe I should specify the length of a, b, c of the unit cell, for the reason that 2D material will have vacuum layer along the c axis.

**Comment by mu-dian** [comment]
I try to add the length of a, b, c in xyz file. Now it can read third order successfully. However, I notice that "Properties=species:S:1:pos:R:3 pbc="T T T"" in xyz file . What is it mean?

**Comment by ZKC19940412** [comment]
Hi, mu-dian. The new information shown in the xyz file is indicating the format of the xyz file. For example, species for each atom is specified by string with 1 character (S1), position is matrix with real numbers in 3 direction (R3), periodic boundary condition is applied along each direction, so pbc is true along x, y, z (pbc="T T T”). You can refer to more detail information about the format in the following ASE website: https://wiki.fysik.dtu.dk/ase/ase/io/formatoptions.html#extxyz.

Hope this helps.

Best, 
Zekun

**Comment by mu-dian** [comment]
Thanks!
