### ISSUE TITLE
How can I calculate eigenvalue values?

### ISSUE THREAD

**Issue by ceceece** [nanotheorygroup/kaldo#94]
I aim to calculate eigenvalue values for the vibrational density of states in the CAS system using LAMMPS's dynamical matrix command. But I cannot get a graph like g(w) (arb. unit)- w(THz) Units do not match each other. Is there another way that I can use to calculate Eigenvalues and Eigenvectors?

**Comment by ZKC19940412** [comment]
Hi, this is Zekun. Thank you so much for reaching out. Based on your workflow, you can access the eigenvectors and eigenvalues after loading the force constants computed using LAMMPS.  

In the attachment,  I also made a coding snippet to help explain things a little bit better:
![eigenvalue_and_eigenvector_code_snippet](https://github.com/nanotheorygroup/kaldo/assets/27995442/592ef8c7-4588-4735-94d3-20d6042714de)

More can also be found in the documentation: https://nanotheorygroup.github.io/kaldo/docsource/api_phonons.html

Hope these help and feel free to let us know if you have other questions regarding using kALDo.

Best, 
Zekun
